# Site Build Settings

# jekyll-paginate configuration
email: f/xgeraadb
paginate:            5
github:
  url: https://wherei.work
# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag, jekyll-maps]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Where I work/today"
description:	       "A blog of places I'd worked"
author:              "Alper Kalaycioglu"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml

maps:
  google:
    api_key: AIzaSyA19aX4EWy5qw_uSpdhg24Ch6-byo4U6pQ